#development: &defaults
#  connection:
#    :access_key_id: AAAAAA_your-key-here
#    :secret_access_key: 4rpsi235js_your-secret-here
#    :use_ssl: true
    # :persistent: true
#  bucket: project-development
#  max_file_size: 10485760
#  acl: public-read